GET http://localhost:3003/api/blogs

###

GET http://localhost:3003/api/users

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "Tuhkimo",
  "name": "Satuhahmo",
  "password": "sekret"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "HTML is easy",
  "author": "Michael Bubble",
  "url": "https://fullstackopen.com/",
  "likes": 5
}

###

GET http://localhost:3003/api/blogs
